#!/usr/bin/with-contenv bash

# add -e -v -d for debugging (syslog-ng --help-all)
exec 2>&1 \
    s6-setuidgid abc /usr/sbin/syslog-ng -F -f /config/syslog-ng.conf --persist-file /config/syslog-ng.persist --pidfile=/config/syslog-ng.pid --control=/config/syslog-ng.ctl --no-caps
